# 例1 线性
![title](pic/1.1.png)

In [2]:
from scipy.optimize import linprog
c = [-4,-3]
A = [[2,1],[1,1]]
b = [10,8]
bounds=((0,None),(0,7))
res = linprog(c,A,b,None,None,bounds,method='simplex')
print('目标函数的最小值：',-res.fun)
print('最优解为：',res.x)

目标函数的最小值： 26.0
最优解为： [2. 6.]


# 例2 线性
![title](pic/1.2.png)

In [1]:
from scipy.optimize import linprog
c = [-2,-3,5]
A = [[-2,5,-1],[1,3,1]]
b = [-10,12]
Aeq = [[1,1,1]]
beq = [7]
bounds=((0,None),(0,None),(0,None))
res = linprog(c,A,b,Aeq,beq,bounds,method='simplex')
print('目标函数的最大值：',-res.fun)
print('最优解为：',res.x)

目标函数的最小值： 14.571428571428571
最优解为： [6.42857143 0.57142857 0.        ]


# 例3 线性
![title](pic/1.3.png)

In [7]:
from scipy.optimize import linprog
c = [2,3,1]
A = [[-1,-4,-2],[-3,-2,0]]
b = [-8,-6]
bounds=((0,None),(0,None),(0,None))
res = linprog(c,A,b,None,None,bounds,method='simplex')
print('目标函数的最小值：',-res.fun)
print('最优解为：',res.x)

目标函数的最小值： -7.0
最优解为： [0.8 1.8 0. ]


# 例4 线性
![title](pic/1.4.png)

In [44]:
from scipy.optimize import linprog
c = [-0.75, -1.05, -0.7753, -1.3611, -1.9148, 0.375, 0.5, 0.4473, 1.2304, 0.35]
A = [[5,10, 0, 0, 0, 0,  0, 0, 0 , 0],
     [0, 0, 7, 9, 12, 0 , 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 6 , 8, 0, 0 , 0],
     [0, 0, 0, 0, 0, 0 , 0, 4, 11 , 0],
     [0, 0, 0, 0, 0, 0 , 0, 0, 0 , 7]]
b = [6000, 10000, 4000, 7000, 4000]
Aeq = [[1, 0, 1, 0, 0, -1, 0, -1, 0, -1],
       [0, 1, 0, 1, 0, 0, -1,  0, 0, 0] ,
       [0, 0, 0, 0, 1, 0,  0,  0, -1, 0]]
beq = [0,0,0]
bounds=((0,None),(0,None),(0,None),(0,None),(0,None),(0,None),(0,None),(0,None),(0,None),(0,None))
res = linprog(c,A,b,Aeq,beq,bounds,method='simplex')
print('目标函数的最大值：',-res.fun)
print('最优解为：',res.x)

目标函数的最大值： 1146.6861576354684
最优解为： [1200.            0.          230.04926108  500.          324.13793103
    0.          500.          858.62068966  324.13793103  571.42857143]


# 例5 线性
![title](pic/1.5.png)

In [25]:
from numpy import log, exp
from scipy.optimize import linprog
c = [log(0.9), log(0.92), log(0.8), log(0.84), log(0.85), log(0.88), log(0.75), log(0.8) ]
A = [[1, 0, 1, 0, 1, 0, 1, 0],
     [0, 1, 0, 1, 0, 1, 0, 1],
     [537.5, 462.5, 560.5, 480, 605, 515, 650, 550]]
b = [48, 32, 48000]
bounds = ((0,None),(0,None),(0,None),(0,None),(0,None),(0,None),(0,None),(0,None))
res = linprog(c,A,b,None,None,bounds,method='simplex')
print('目标函数的最大值：',1-exp(res.fun))
print('最优解为：',res.x)

目标函数的最大值： 0.99999999889648
最优解为： [ 0.          0.          0.          0.          0.          0.
 48.         30.54545455]


# 例6 线性 绝对值
![title](pic/1.6.png)

In [39]:
from scipy.optimize import linprog
c = [1,1,2,2,3,3,4,4]
Aeq = [[ 1, -1, -1,  1, -1,  1,  1, -1],
       [ 1, -1, -1,  1,  1, -1, -3,  3],
       [ 1, -1, -1,  1, -2,  2,  3, -3],
       [-1, -1,  0,  0,  0,  0,  0,  0],
       [ 0,  0, -1, -1,  0,  0,  0,  0],
       [ 0,  0,  0,  0, -1, -1,  0,  0],
       [ 0,  0,  0,  0,  0,  0, -1, -1]]

beq = [0, 1, -0.5, 0, 0, 0,  0]
bounds = ((None,None),(None,None),(None,None),(None,None),(None,None),(None,None),(None,None),(None,None))
res = linprog(c,None,None,Aeq,beq,bounds=bounds,method='simplex')
print('目标函数的最小值：',res.fun)
print('最优解为：',res.x)

目标函数的最小值： 0.0
最优解为： [ 0.125 -0.125  0.     0.     0.     0.    -0.125  0.125]


d:\program files (x86)\python release\python37\lib\site-packages\ipykernel_launcher.py:13: OptimizeWarning: A_eq does not appear to be of full row rank. To improve performance, check the problem formulation for redundant equality constraints.
  del sys.path[0]


# 例7 线性
![title](pic/1.7.png)

In [43]:
c = [-3100, -3100, -3100, -3800, -3800, -3800, -3500, -3500, -3500, -2850, -2850, -2850]
A = [[1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0],
     [0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0],
     [0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1],
     [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
     [480, 0, 0, 650, 0, 0, 580, 0, 0, 390, 0, 0],
     [0, 480, 0, 0, 650, 0, 0, 580, 0, 0, 390, 0],
     [0, 0, 480, 0, 0, 650, 0, 0, 580, 0, 0, 390]]
b = [10, 16,8,18,15,23,12,6800,8700,5300]

Aeq = [[8, -5,  0, 8, -5,  0, 8, -5,  0, 8, -5,  0],
       [0,  1, -2, 0,  1, -2, 0,  1, -2, 0,  1, -2],
       [4,  0, -5, 4,  0, -5, 4,  0, -5, 4,  0, -5]]
beq = [0,0,0]
bounds = ((0,None),(0,None),(0,None),(0,None),(0,None),(0,None),(0,None),(0,None),(0,None),(0,None),(0,None),(0,None))
res = linprog(c,A,b,Aeq,beq,bounds=bounds,method='simplex')
print('目标函数的最大值：',-res.fun)
print('最优解为：',res.x)

目标函数的最大值： 121515.78947368421
最优解为： [ 0.          0.          0.          7.          0.          8.
  3.         12.94736842  0.          0.          3.05263158  0.        ]


d:\program files (x86)\python release\python37\lib\site-packages\ipykernel_launcher.py:19: OptimizeWarning: A_eq does not appear to be of full row rank. To improve performance, check the problem formulation for redundant equality constraints.


# 例8 整数 指派问题
![title](pic/1.8.png)

**第一种解法**

In [46]:
import numpy as np
from scipy import optimize
c = [[15, 18, 21, 24], 
     [19, 23, 22, 18], 
     [26, 17, 16, 19],
     [19, 21, 23, 17]]
c = np.array(c)
row_index, col_index=optimize.linear_sum_assignment(c)
print(row_index,col_index)
print('最小值',c[row_index,col_index].sum())

[0 1 2 3] [0 3 2 1]
最小值 70


**第二种解法**

In [60]:
import cvxpy as cp 
import numpy as np 
c=np.array([[15, 18, 21, 24], 
            [19, 23, 22, 18], 
            [26, 17, 16, 19],
            [19, 21, 23, 17]]) 
x = cp.Variable((4,4),integer=True)
obj = cp.Minimize(cp.sum(cp.multiply(c,x))) 
con= [0 <= x, x <= 1, cp.sum(x, axis=0, keepdims=True)==1, 
               cp.sum(x, axis=1, keepdims=True)==1] 
prob = cp.Problem(obj, con) 
prob.solve(solver='GLPK_MI') 
print("最优值为:",prob.value) 
print("最优解为：\n",x.value)

最优值为: 70.0
最优解为：
 [[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]


# 例9 线性整数
![title](pic/1.9.png)

In [1]:
import cvxpy as cp 
from numpy import array 
c=array([1,1])  # 定义目标向量 
a=array([[1, 9/14], [-2,1]])  # 定义约束矩阵 
b=array([51/14, 1/3])  # 定义约束条件的右边向量 
x=cp.Variable(2,integer=True)  # 定义两个整数决策变量 
obj=cp.Maximize(c*x)  # 构造目标函数
cons=[a*x<=b, x>=0]    #构造约束条件 
prob=cp.Problem(obj, cons)  # 构建问题模型 
prob.solve(solver='GLPK_MI',verbose =True)  # 求解问题求解问题 
print("最优值为:",prob.value) 
print("最优解为：\n",x.value)

Using the Community license in this session. If you have a full Xpress license, first set the XPAUTH_PATH environment variable to the full path to your license file, xpauth.xpr, and then restart Python. If you want to use the FICO Community license and no longer want to see this message, set the XPAUTH_PATH environment variable to: d:\program files (x86)\python release\python37\lib\site-packages\xpress\license\community-xpauth.xpr
NB: setting XPAUTH_PATH will also affect any other Xpress products installed on your system.
最优值为: 4.0
最优解为：
 [2. 2.]


d:\program files (x86)\python release\python37\lib\site-packages\cvxpy\expressions\expression.py:550: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.

  warnings.warn(__STAR_MATMUL_WARNING__, UserWarning)
d:\program files (x86)\python release\python37\lib\site-packages\cvxpy\expressions\expression.py:550: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.

  warnings.warn(__STAR_MATMUL_WARNING__, UserWarning)


# 例10 整数
![title](pic/1.10.png)

In [4]:
from scipy.optimize import linprog
c1 = [-4.8, -5.6, -4.8, -5.6, 10]
c2 = [-4.8, -5.6, -4.8, -5.6, 8]
c3 = [-4.8, -5.6, -4.8, -5.6, 6]

A = [[-1, 0, 1, 0, 0],
     [0, -2, 0, 3, 0],
     [1, 1, 0, 0, -1],
     [0, 0, 1, 1, 0]]
b = [0, 0, 500,1000]
bounds1 = ((0,None),(0,None),(0,None),(0,None),(0,500))
bounds2 = ((0,None),(0,None),(0,None),(0,None),(500,1000))
bounds3 = ((0,None),(0,None),(0,None),(0,None),(1000,1500))
res = linprog(c1,A,b,None,None,bounds1,method='simplex')
print('目标函数的最大值：',-res.fun)
print('最优解为：',res.x)
res = linprog(c2,A,b,None,None,bounds2,method='simplex')
print('目标函数的最大值：',-res.fun-1000)
print('最优解为：',res.x)
res = linprog(c3,A,b,None,None,bounds3,method='simplex')
print('目标函数的最大值：',-res.fun-3000)
print('最优解为：',res.x)

目标函数的最大值： 4800.0
最优解为： [500.   0. 500.   0.   0.]
目标函数的最大值： 5000.0
最优解为： [2.27373675e-13 1.50000000e+03 2.27373675e-13 1.00000000e+03
 1.00000000e+03]
目标函数的最大值： 5000.0
最优解为： [5.68434189e-14 1.50000000e+03 0.00000000e+00 1.00000000e+03
 1.00000000e+03]


# 例11 整数
![title](pic/1.11.png)

In [58]:
A = [[0, 4, 6, 7, 7, 7, 7],
     [0, 2, 4, 6, 8, 9, 10],
     [0, 3, 5, 7, 8, 8, 8],
     [0, 4, 5, 6, 6, 6, 6],
     [0, 0, 0, 0, 0, 0, 0]]
n = 6
res = []
def bfs(nums,count,index,path):

    if count==6 and len(path)==4:
        res.append(path)
    if index==4:
        return
    for i in range(len(nums)):
        bfs(A[index+1][:n-i-count+1],count+i,index+1,path+[nums[i]])
bfs(A[0],0,0,[])
max_interest = max([ sum(i) for i in res])
print('最大利润',max_interest)
print('甲乙丙丁的分配方式为',[i  for i in res if sum(i)==max_interest])
    

最大利润 17
甲乙丙丁的分配方式为 [[4, 2, 7, 4], [4, 4, 5, 4], [4, 6, 3, 4], [6, 0, 7, 4], [6, 2, 5, 4], [6, 4, 3, 4]]


# 例题 12
![title](pic/1.12.1.png)
![title](pic/1.12.2.png)
![title](pic/1.12.3.png)

In [1]:
import numpy as np
import cvxpy as cp
badA = np.array([[8.4, 8.4, 9.1, 8.7],
              [9.3, 8.4, 8.4, 8.9],
              [8.4, 8.1, 8.4, 9.5],
              [8.1, 8.7,   9, 8.4],
              [8.4,   9, 8.3, 9.4],
              [9.4, 8.7, 8.5, 8.4],
              [9.5, 8.4, 8.3, 8.4],
              [8.4, 8.8, 8.7, 8.2],
              [8.4, 8.4, 8.4, 9.3],
              [  9, 8.1, 8.2, 9.1]])
goodA = np.array([[9.25,    9,   9.5,   9.1],
                  [ 9.6,    9,     9,   9.3],
                  [   9,  9.1,  9.25,   9.8],
                  [ 9.1,  9.1,   9.5,     9],
                  [9.25,  9.4,   8.9,   9.7],
                  [ 9.7,  9.1,   8.9,  9.25],
                  [ 9.8,    9,   8.9,   9.2],
                  [   9,  9.8,   9.1,   9.3],
                  [9.25,  9.2,     9,   9.7],
                  [ 9.4,  9.1,   9.2,   9.5]])
# 求解函数
def dp(A,index,ssum,path):
    global ans,ansPath,ansLeft
    if len(path)==4:
        # 下面是整数规划问题
        left = [i  for i in range(n) if i not in path]
        c = A[[left]]
        x = cp.Variable((6,4),integer=True)
        obj = cp.Maximize( cp.sum(cp.multiply(c,x)) + ssum)
        con = [0 <= x, x <= 1, cp.sum(x, axis=0, keepdims=True)<=2,
                               cp.sum(x, axis=1, keepdims=True)<=3]
        prob = cp.Problem(obj, con)
        prob.solve(solver = 'GLPK_MI')
        if ans < prob.value:
            ans = prob.value
            ansLeft = x.value
            ansPath = np.array(path)
        return
    for i in range(index,n):
        dp(A,i+1,ssum+sum(A[i]),path+[i])
        
# 输出答案
def printAns(ans, ansPath, ansLeft,condition):
    
    sports = ['高低杠','平衡木','跳马','自由体操']
    print(condition+'的情况下最优值是',ans)
    print(condition+'的情况下全能选手是',ansPath+1)
    print(condition+'的情况下,其余选手')
    for i,j in zip([i  for i in range(n) if i not in ansPath],ansLeft):
        print(i+1,end=' ')
        for k in range(len(j)):
            if j[k]:
                print(sports[k],end=' ')
        print()
n = 10

Using the Community license in this session. If you have a full Xpress license, first set the XPAUTH_PATH environment variable to the full path to your license file, xpauth.xpr, and then restart Python. If you want to use the FICO Community license and no longer want to see this message, set the XPAUTH_PATH environment variable to: d:\program files (x86)\python release\python37\lib\site-packages\xpress\license\community-xpauth.xpr
NB: setting XPAUTH_PATH will also affect any other Xpress products installed on your system.


**第一问**

In [2]:
for A,condition in zip((badA,goodA),('最差','期望')):
    ans = 0
    ansLeft ,ansPath = [],[]
    dp(A,0,0,[])
    printAns(ans, ansPath, ansLeft, condition)
    print()


d:\program files (x86)\python release\python37\lib\site-packages\ipykernel_launcher.py:29: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


最差的情况下最优值是 212.3
最差的情况下全能选手是 [2 5 6 9]
最差的情况下,其余选手
1 跳马 
3 自由体操 
4 平衡木 跳马 
7 高低杠 
8 平衡木 
10 高低杠 自由体操 

期望的情况下最优值是 225.10000000000002
期望的情况下全能选手是 [ 2  3  9 10]
期望的情况下,其余选手
1 跳马 
4 跳马 
5 平衡木 自由体操 
6 高低杠 
7 高低杠 
8 平衡木 自由体操 



**第二问**