# 数据的检验与处理
![title](pic\3.1.1.png)

In [1]:
import numpy as np
import math
data = (3,8,10,14,17)
c = 10
n  = len(data)
X0 = np.array(data)+c

lam = np.array([X0[i-1]/X0[i] for i in range(1,n)])
print(lam)

# 级比检验
if all( lam > math.exp(-2/(n+1))) and all(lam < math.exp(2/(n+1))):
    print('通过级比检验')
else:
    print('没有通过级比检验')

[0.72222222 0.9        0.83333333 0.88888889]
通过级比检验


# 建立模型
![title](pic\3.1.2.png)

In [2]:
# 累加生成
X1 = X0.cumsum()


# 计算数据矩阵B和数据向量Y
alpha = 0.5
B = np.zeros([n-1,2])
Y = np.zeros([n-1,1])
for i in range(n-1):
    B[i][0] = -alpha*X1[i]+(alpha-1)*X1[i+1]
    B[i][1] = 1
    Y[i][0] = X0[i+1]
    
    
#计算GM(1,1)微分方程的参数a和u
A = np.linalg.inv(B.T.dot(B)).dot(B.T).dot(Y)
a,u = A


#建立灰色预测模型
XX0 = np.zeros(n)
XX0[0] = X0[0]
for i in range(1,n):
    XX0[i] = (X0[0] - u/a)*(1-math.exp(a))*math.exp(-a*(i));

array([13.        , 17.7785049 , 20.44980597, 23.52248215, 27.05684188])

# 检验预测值
![title](pic\3.1.3.png)

In [3]:
#（1）残差检验
e = np.array([1- XX0[i]/X0[i] for i in range(n)])
print('残差检验')
if all(e<0.1):
    print('可以达到较高要求')
elif all(e<0.2):
    print('可以达到一般要求')
else:
    print('不通过',e)

#（2）级比偏差值检验
p = 1 - (2-a)/(2+a)*lam
print('级比偏差值检验')
if all(p<0.1):
    print('可以达到较高要求')
elif all(p<0.2):
    print('可以达到一般要求')
else:
    print('不通过',p)

残差检验
可以达到较高要求
级比偏差值检验
可以达到一般要求


# 预测报告
![title](pic\3.1.4.png)

In [14]:
def fun(n,sep = 10,X=X0,a_=a,u_=u):
    f = [(X[0] - u/a)*(1-math.exp(a))*math.exp(-a*(i)) for i in range(n,n+sep)]
    return f
fun(n)


[array([31.12225521]),
 array([35.79851534]),
 array([41.17740479]),
 array([47.36449679]),
 array([54.48122746]),
 array([62.66727922]),
 array([72.08332241]),
 array([82.91416884]),
 array([95.37239912]),
 array([109.70253506])]